service: serverless-vaporeon

useDotenv: true

plugins:
  - serverless-plugin-optimize
  - serverless-offline
  
custom:
  serverless-offline:
    httpPort: 4000
    websocketPort: 4001
    lambdaPort: 4002

provider:
  name: aws
  timeout: 900
  runtime: nodejs18.x
  environment:
    PORT: ${env:PORT}
    APP_ENVIRONMENT: ${env:APP_ENVIRONMENT}

    DB_NAME: ${env:DB_NAME}
    DB_URL: ${env:DB_URL}

functions:
  main:
    handler: dist/lambda.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'
